apiVersion: v1
kind: ConfigMap
metadata:
  name: iggy-config
  namespace: tracker
data:
  server.toml: |
    [system]
    path = "local_data"

    [system.logging]
    path = "logs"
    level = "info"
    max_size = "512 MB"
    retention = "7 days"

    [system.cache]
    enabled = true
    size = "512 MB"

    [system.stream]
    path = "streams"

    [system.topic]
    path = "topics"
    max_size = "unlimited"
    delete_oldest_segments = false

    [system.partition]
    path = "partitions"
    messages_required_to_save = 1000
    enforce_fsync = false
    validate_checksum = false

    [system.segment]
    size = "1 GB"
    message_expiry = "none"
    server_confirmation = "wait"
    cache_indexes = true

    [system.encryption]
    enabled = false

    [system.state]
    enforce_fsync = false

    [message_saver]
    enabled = true
    enforce_fsync = true
    interval = "30 s"

    [data_maintenance.archiver]
    enabled = false
    kind = "disk"

    [tcp]
    enabled = true
    address = "0.0.0.0:8090"

    [http]
    enabled = true
    address = "0.0.0.0:3000"

    [http.cors]
    enabled = true
    allowed_methods = ["GET", "POST", "PUT", "DELETE"]
    allowed_origins = ["*"]
    allowed_headers = ["content-type"]

    [http.jwt]
    algorithm = "HS256"
    audience = "iggy.rs"

    [quic]
    enabled = false

    [telemetry]
    enabled = false
